# Generated by Django 3.1.2 on 2020-10-18 16:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_capacity', models.IntegerField()),
                ('web_support', models.BooleanField()),
                ('shape', models.CharField(choices=[('oval', 'oval'), ('rectangular', 'rectangular'), ('canopy', 'canopy'), ('elevated', 'elevated')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('doj', models.DateField(verbose_name='date of joining')),
                ('standard', models.CharField(max_length=255)),
                ('ranking', models.IntegerField()),
                ('point_of_contacts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chapters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('total_duration', models.IntegerField(verbose_name='total duration in minutes')),
                ('class_duration', models.IntegerField(verbose_name='average duration in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doj', models.DateField(verbose_name='date of joining')),
                ('salary', models.FloatField(verbose_name='in hand salary LPA')),
                ('twl', models.BooleanField(verbose_name='takes web lecture')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.classroom'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.teacher'),
        ),
    ]
