# Generated by Django 3.1.2 on 2020-10-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassStudents',
            new_name='ClassStudent',
        ),
    ]
