# Generated by Django 3.1.2 on 2020-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20201018_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='college.Subject'),
        ),
    ]
