# Generated by Django 3.1.2 on 2020-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='college.Student'),
        ),
    ]
