# Generated by Django 3.1.2 on 2020-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_class_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='point_of_contacts',
        ),
        migrations.AddField(
            model_name='student',
            name='point_of_contacts',
            field=models.ManyToManyField(to='college.StudentContact'),
        ),
    ]
