# Generated by Django 3.1.2 on 2020-10-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20201020_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_id',
            new_name='class_room_id',
        ),
    ]
