# Generated by Django 3.1.2 on 2020-10-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20201020_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='point_of_contacts',
        ),
        migrations.AddField(
            model_name='studentcontact',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.student'),
            preserve_default=False,
        ),
    ]
